### ISSUE TITLE
Population sub-indexing not implemented

### ISSUE THREAD

**Issue by astoeckel** [SpiNNakerManchester/sPyNNaker#163] opened 2015-10-28 11:57 UTC
The following code:

``` python
import pyNN.spiNNaker as sim

sim.setup()
p = sim.Population(3, sim.SpikeSourceArray, {"spike_times": []})
p[0]
```

Crashes with

```
NotImplementedError                       Traceback (most recent call last)
<ipython-input-22-a69904524460> in <module>()
----> 1 p[0]

/usr/lib/python2.7/site-packages/spynnaker/pyNN/models/pynn_population.pyc in __getitem__(self, index_or_slice)
    155     def __getitem__(self, index_or_slice):
    156         # TODO: Used to get a single cell - not yet supported
--> 157         raise NotImplementedError
    158 
    159     def get(self, paramter_name, gather=False):

NotImplementedError: 
```

**Comment by Christian-B** [comment] 2017-07-28 09:12
Duplicate of https://github.com/SpiNNakerManchester/sPyNNaker/issues/160

Also a longer term project so no need for multiple issues.

**Closed by Christian-B** 2017-07-28 09:12 UTC
