### ISSUE TITLE
IndexError when using unconnected SpikeSourceArray

### ISSUE THREAD

**Issue by astoeckel** [SpiNNakerManchester/sPyNNaker#191] opened 2016-02-10 17:06 UTC
Consider the following PyNN program, which creates two spike sources and a single population of neurons. Only one of the spike sources projects onto the neuron population, the other population is not connected to anything:

```python
import pyNN.spiNNaker as sim

sim.setup()

p1 = sim.Population(3, sim.SpikeSourceArray, {"spike_times":  [1.0, 2.0, 3.0]})
p2 = sim.Population(3, sim.SpikeSourceArray, {"spike_times":  [[10.0], [20.0], [30.0]]})
p3 = sim.Population(4, sim.IF_cond_exp, {})

sim.Projection(p2, p3, sim.FromListConnector([
    (0, 0, 0.1, 1.0), (1, 1, 0.1, 1.0), (2, 2, 0.1, 1.0)]))
#sim.Projection(p1, p3, sim.FromListConnector([(0, 3, 0.1, 1.0)])) # works if this line is added

sim.run(100.0)
```

Running this program results in the following runtime exception:

```
  File "spinnaker_bug.py", line 13, in <module>
    sim.run(100.0)
  File "/home/andreas/source/spinnaker/sPyNNaker/spynnaker/pyNN/__init__.py", line 186, in run
    _spinnaker.run(run_time)
  File "/home/andreas/source/spinnaker/sPyNNaker/spynnaker/pyNN/spinnaker.py", line 301, in run
    config.getboolean("Reports", "outputTimesForSections"))
  File "/home/andreas/source/spinnaker/SpiNNFrontEndCommon/spinn_front_end_common/utilities/helpful_functions.py", line 268, in do_mapping
    pacman_executor.execute_mapping()
  File "/home/andreas/source/spinnaker/PACMAN/pacman/operations/pacman_algorithm_executor.py", line 261, in execute_mapping
    self._handle_internal_algorithm(algorithm)
  File "/home/andreas/source/spinnaker/PACMAN/pacman/operations/pacman_algorithm_executor.py", line 287, in _handle_internal_algorithm
    results = python_algorithm(**inputs)
  File "/home/andreas/source/spinnaker/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/front_end_common_partitionable_graph_data_specification_writer.py", line 46, in __call__
    write_text_specs, app_data_runtime_folder)
  File "/home/andreas/source/spinnaker/SpiNNFrontEndCommon/spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py", line 224, in generate_data_spec
    write_text_specs, application_run_time_folder)
  File "/home/andreas/source/spinnaker/SpiNNFrontEndCommon/spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_partitioned_vertex.py", line 410, in generate_data_spec
    self._update_virtual_key(routing_info, sub_graph)
  File "/home/andreas/source/spinnaker/SpiNNFrontEndCommon/spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_partitioned_vertex.py", line 343, in _update_virtual_key
    sub_graph.outgoing_subedges_from_subvertex(self)[0])
```

Inserting a projection between the previously unconnected SpikeSourceArray and the neuron population solves this problem.

Note that I'm aware that a unconnected SpikeSourceArray is not that useful -- yet it should not cause a crash. ;-)

**Comment by alan-stokes** [comment] 2016-02-10 17:45
funny that ;-) nonsense in nonsense out and all that.
the error still exists in the master version of github, but with a different error message.

    self._write_configuration(spec, routing_info, sub_graph, ip_tags)
  File "/home/alan/spinnaker/alpha_package_103_git/SpiNNFrontEndCommon/spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_partitioned_vertex.py", line 382, in _write_configuration
    spec.write_value(data=self._virtual_key)
  File "/home/alan/spinnaker/alpha_package_103_git/DataAllocation/data_specification/data_specification_generator.py", line 914, in write_value
    "data", data, data_type.min, data_type.max, Commands.WRITE.name)
DataSpecificationParameterOutOfBoundsException

the issue is how to tell a core not to transmit when it actually has a spike. firing with any random key is royally bad idea. A flag stating do transmit or not slows down the c code as we'd need to check each time we want to fire a spike.......

**Comment by astoeckel** [comment] 2016-02-10 17:49
Probably stupid proposal from my side: couldn't you "just" prune the unconnected graph component away?

**Comment by AlexRast** [comment] 2016-02-10 22:29
OK, here's a bizarre but possible hypothetical.

What if you instantiate a SpikeSourceArray to provide a source of input to an 
external device? You don't create any projections from it because it's only 
going to go out as an external stimulus via a LivePacketGatherer. But maybe in 
turn that external device itself projects back in, or is in fact some sort of 
actuator, or whatever that changes external conditions and leads to a different 
result in the total simulation? Will this work? Has anyone tested such a condition?

I think this should work because there is at least one destination for the 
SpikeSourceArray, but there is a question here because as the system is now 
projections aren't set up in the PyNN script to do this; it's done behind the 
scenes.

Meanwhile I can also see situations where pruning the supposedly unwanted 
population wouldn't be what was wanted. Perhaps someone is setting up a 
simulation where they want to compare an output from a network against a 
reference - defined by the SpikeSourceArray. Or use its spikes to configure 
post-mortem spike analysis. Or something else like that. Not sure it can always 
be assumed that an unconnected population is doing nothing.

**Comment by rowleya** [comment] 2016-02-11 07:40
I have made a fix to this a little while ago in a branch (accumulator_updates I think).  This allows you to run a SpikeSourceArray without connections, meaning that it doesn't send any actual spikes, but does still allow recording of spikes should this be desired.

For interest, the issue was simply that there was no key assigned to the array for transmission as it had no outgoing edges.  If you enabled live output, an outgoing edge was added to the LivePacketGather vertex, so it then worked.  The solution adds a flag indicating whether packets should actually be sent; if the flag says *not* to send packets, the key is set to 0 (as it doesn't matter, as nothing will be sent anyway).

**Comment by AlexRast** [comment] 2016-02-11 15:37
'Ordinary' neurons have a use_key flag in neuron.c that does the same thing, 
presumably to handle the obvious case of a feedforward network with an output 
layer (which doesn't have any outward projections but needs to be recorded 
because otherwise you're not getting the 'result' of the simulation). Is that 
what accumulator_updates adds? If not then this would seem to be the general 
approach that should be taken, so that all populations of any type always have a 
use_key flag.

**Comment by rowleya** [comment] 2016-02-11 15:38
Yes, this is pretty much what the change in accumulator updates does for SpikeSourceArray.

**Comment by alan-stokes** [comment] 2016-03-24 10:43
this has been fixed in the GFE prov after crash brnach (which was checked against accumulator updates) as GFE branch is the last branch to be merged before the release. So should be in Another FineProduct From The Nonesense Factory release. Therefore closing this issue.

**Closed by alan-stokes** 2016-03-24 10:43 UTC
Labels: bug
