### ISSUE TITLE
Insufficient checking on spike delay timer.

### ISSUE THREAD

**Issue by SimonDavidson** [SpiNNakerManchester/sPyNNaker#431] opened 2017-11-17 12:05 UTC
In file sPyNNaker/neural_modelling/src/neuron/neuron.c, beginning at line 443.

While loop to wait enough time to space out spikes. 

If the while loop is interrupted and the timer wraps around during the time when the interrupt is being serviced, when it returns from the interrupt it must wait for the timer to count down almost the entire timer tick again before continuing.

Solution may be to check (inside the while loop) if a timer wraparound has occurred and to escape the wait loop immediately if this is the case.

**Comment by rowleya** [comment] 2017-11-17 14:23
This is true - the issue is that if you overrun your timer just once, you will probably get stuck always overrunning it!

Another idea is to set up timer2 to be the same as timer 1 but without looping.  Then you can just run the check on timer2.  Alternatives include setting up timer2 with the actual wait time and then having a spin1_wfi to wait for the interrupt.

**Comment by alan-stokes** [comment] 2017-11-17 14:51
so just quickly jumping in as a fly by. But if that's to do with the spreader. we did some stuff with icub code for tdma'ing so that we handle the edge case. code below: 

 //calculate max_counter;
       max_counter = timer_period * sv->cpu_clk;


       int dt = current_time - tc[T1_COUNT];
       if(dt < 0) dt += max_counter;
       while(dt < my_tdma_id * TDMA_WAIT_PERIOD) {
            dt = current_time - tc[T1_COUNT];
            if(dt < 0) dt += max_counter;
       }

woudl that help you guys at all?

**Comment by rowleya** [comment] 2017-11-17 14:54
Not sure - looks like that could work too.

**Comment by alan-stokes** [comment] 2017-11-17 14:56
if so, big thanks go to Arren Glover who generated that code in the first place.

**Comment by andrewgait** [comment] 2019-07-22 15:08
I think the code in neuron.c has been updated to take this issue into account, so this can probably be closed?

**Comment by rowleya** [comment] 2019-07-22 15:46
Fixed in #539

**Closed by rowleya** 2019-07-22 15:46 UTC
Labels: bug
