### ISSUE TITLE
stdp can also run out of SDRAM

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#636] opened 2019-04-11 08:32 UTC
Script:  (stripped down vogels_2011  Not using vogels)
import spynnaker8 as sim

NUM_EXCITATORY = 2000

sim.setup(timestep=1.0, min_delay=1.0, max_delay=10.0)
sim.set_number_of_neurons_per_core(sim.IF_curr_exp, 10)

ex_pop = sim.Population(NUM_EXCITATORY, sim.IF_curr_exp)
in_pop = sim.Population(NUM_EXCITATORY / 4, sim.IF_curr_exp)

ex_pop.record(['spikes'])

sim.Projection(ex_pop, in_pop, sim.FixedProbabilityConnector(0.02),
               receptor_type='excitatory',
               synapse_type=sim.StaticSynapse(weight=0.03))
sim.Projection(ex_pop, ex_pop, sim.FixedProbabilityConnector(0.02),
               receptor_type='excitatory',
               synapse_type=sim.StaticSynapse(weight=0.03))

sim.Projection(in_pop, in_pop,  sim.FixedProbabilityConnector(0.02),
               receptor_type='inhibitory',
               synapse_type=sim.StaticSynapse(weight=-0.3))

ie_projection = sim.Projection(
    in_pop, ex_pop, sim.FixedProbabilityConnector(0.02),
    receptor_type='inhibitory', synapse_type=synapse_type=sim.StaticSynapse(weight=-0.3))

sim.run(1200000)
sim.end()

Error during:
            spinn_front_end_common/interface/interface_functions/chip_runtime_updater.py

2019-04-11 09:30:56 ERROR: 1, 0, 12: RUN_TIME_EXCEPTION (API) IF_curr_exp_std
2019-04-11 09:30:56 ERROR: r0=0x00000013 r1=0x00000000 r2=0x00004000 r3=0x00003304
2019-04-11 09:30:56 ERROR: r4=0x603937F0 r5=0x00400018 r6=0x00000001 r7=0x00000000
....
2019-04-11 09:30:59 ERROR: 1, 0, 12: Could not allocate recording region 0 of 8094032 bytes (recording.c: 589)
.....

**Comment by Christian-B** [comment] 2019-04-11 08:32
related to https://github.com/SpiNNakerManchester/sPyNNaker/issues/620

**Comment by Christian-B** [comment] 2019-04-11 08:48
Removed stdp from original script and it still fails.

**Comment by Christian-B** [comment] 2019-04-11 09:00
Alan suggests using AbstractPopulationVertex.get_sdram_usage_for_atoms while getting costs for auto pause resume

**Comment by Christian-B** [comment] 2019-04-11 09:42
I added the line
            log_info("max %u ",sark_heap_max(sv->sdram_heap, ALLOC_LOCK));

in recording.c just above the sark_xalloc that fails and it often reports:
[INFO] (recording.c: 583): max 3842050060

Which claims there is 3.57 GIGA bytes of sdram

**Comment by Christian-B** [comment] 2019-04-11 10:26
I changed recordind.c method recording_initialize
        spin1_delay_us(spin1_get_core_id()*1000);
        uint32_t size = (uint32_t) recording_data->region_pointers[
            n_recording_regions + counter];
        if (size > 0) {
            region_sizes[counter] = size;
            log_info("max %u ",sark_heap_max(sv->sdram_heap, ALLOC_LOCK));
            region_addresses[counter] = sark_xalloc(
                sv->sdram_heap, size + sizeof(recording_channel_t), 0, ALLOC_LOCK);
            log_info("max %u ",sark_heap_max(sv->sdram_heap, ALLOC_LOCK));
            if (region_addresses[counter] == NULL) {
                log_error(
                    "Could not allocate recording region %u of %u bytes",
                    counter, size);
                return false;
            }
            log_info("region %u ",region_addresses[counter]);



Note: the delay based on core id so that sark_xalloc are happeding one core at a time.

We now see that is is always core 16 that fails!
[INFO] (recording.c: 554): Recording 4 regions, using output tag 2, size before trigger 2545788, time between triggers 250
[INFO] (recording.c: 584): max 84448108
[INFO] (recording.c: 587): max 83985252
[INFO] (recording.c: 594): region 1651993740
[INFO] (recording.c: 584): max 40710664
[INFO] (recording.c: 587): max 38165100
[INFO] (recording.c: 594): region 1695731184
[INFO] (recording.c: 584): max 15255024
[INFO] (recording.c: 587): max 12709460
[INFO] (recording.c: 594): region 1721186824
[INFO] (recording.c: 584): max 2527204
[INFO] (recording.c: 587): max 2527204
[ERROR] (recording.c: 591): Could not allocate recording region 3 of 2545532 bytes

the size asked for is 18328 bytes of 17.9 kb off

**Comment by dkfellows** [comment] 2019-04-11 10:40
**CRITICAL:** all accesses to the SDRAM heap that are not strictly single-threaded on a whole-chip level _must_ pass the `ALLOC_LOCK` flag, whether they are allocations, frees or queries of the heap allocation unit size. Note that SCAMP always gets this right; it insists on holding the lock when you access the global heap.

And there's a race anyway if you query the size and use that to make a decision on whether to allocate. (It's not critical here… but it's important if you're DIY.)

(This message is because @Christian-B asked me to note it.)

**Comment by Christian-B** [comment] 2019-04-12 09:48
Error was get_max_atoms_per_core() had been stripped out so n_atoms was being used.

**Comment by Christian-B** [comment] 2019-04-12 09:54
Fixed with ALL THREE prs at the same time.

**Comment by andrewgait** [comment] 2019-07-18 16:19
Confirmed that this script now runs without errors, so closing this issue.

**Closed by andrewgait** 2019-07-18 16:19 UTC
Labels: bug
