### ISSUE TITLE
Spike recording failing in python 2.7

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/sPyNNaker#647] opened 2019-05-15 15:39 UTC
The following script works in python 3 (3.5 to be more precise) but not in python 2.7.

import spynnaker8 as p

p.setup(timestep=1.0)

simtime = 300

pop_src2 = p.Population(1, p.SpikeSourcePoisson(rate=10), label="drive")
pop_ex = p.Population(1, p.IF_curr_exp(), label="test")

proj2 = p.Projection(pop_src2,  pop_ex,  p.OneToOneConnector(),
               synapse_type=p.StaticSynapse(weight=2.0),  receptor_type='excitatory')

pop_src2.record(['spikes'])
pop_ex.record('spikes')

p.run(simtime)

pop_ex.get_data('spikes')
pop_src2.get_data('spikes')

p.end()
print("\n job done")

The error in python 2.7 is

Traceback (most recent call last):
  File "/localhome/mbbssag3/spinnaker/git/MySpiNNakerProblems/user_problems/pynn0.8/test_poisson_recording.py", line 19, in <module>
    pop_src2.get_data('spikes')
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/spynnaker8/models/populations/population.py", line 259, in get_data
    return self._extract_neo_block(variables, None, clear, annotations)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/spynnaker8/models/recorder.py", line 55, in _extract_neo_block
    self._append_current_segment(block, variables, view_indexes, clear)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/spynnaker8/models/recorder.py", line 160, in _append_current_segment
    spikes=self._get_spikes(),
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker/spynnaker/pyNN/models/recording_common.py", line 221, in _get_spikes
    sim.machine_time_step)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker/spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py", line 703, in get_spikes
    placements, graph_mapper, self, machine_time_step)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker/spynnaker/pyNN/models/common/multi_spike_recorder.py", line 71, in get_spikes
    neuron_param_data, spike_ids, spike_times)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker/spynnaker/pyNN/models/common/multi_spike_recorder.py", line 99, in _process_spike_data
    count=n_bytes_per_block * n_blocks, offset=offset)
AttributeError: 'memoryview' object has no attribute '__buffer__'

**Comment by rowleya** [comment] 2019-05-15 17:56
I started fixing this at the target, but have looked and the issue is likely to occur all over the place.  The issue is that numpy.frombuffer can't take a memoryview in Python 2.  So it looks like the code needs to return a bytearray to the caller in Python 2, which I think it used to.

**Comment by rowleya** [comment] 2019-05-15 17:59
I believe the culprit line is here:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/spinn_front_end_common/interface/buffer_management/storage_objects/sqllite_database.py#L64

Removing the surrounding memoryview should fix it I guess?

**Comment by rowleya** [comment] 2019-05-16 11:01
Fixed and merged

**Closed by rowleya** 2019-05-16 11:01 UTC
Labels: bug
