### ISSUE TITLE
pop.set(.. followed by pop.reset(... causes state variables not to be reloaded.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#599] opened 2019-02-26 14:40 UTC
Script:
import spynnaker8 as sim

sim.setup(1.0)
pop = sim.Population(1, sim.IF_curr_exp, {}, label="pop")
pop.set(i_offset=1.0)
pop.set(tau_syn_E=1)
pop.record(["v"])
sim.run(5)
pop.set(tau_syn_E=1)
#sim.run(5)
v1 = pop.spinnaker_get_data('v')
sim.reset()
sim.run(5)
#sim.run(5)
v2 = pop.spinnaker_get_data('v')
sim.end()
print(v1)
print(v2)

If you uncomment the second runs the states are reset correctly.

If you do 
pop.initialize(v=.60) nar the reset ONLY v is reset the other states gsyn_exc remain unchanged.
(note not checkable with this script as gsyn_exc is zero)

**Comment by Christian-B** [comment] 2019-02-26 14:42
Or more likely is is setting the state variables but to the values it obtained to do second pop.set(tau_syn_E=1)

**Comment by andrewgait** [comment] 2019-02-26 16:03
In a similar vein to the above script,

import spynnaker8 as sim

sim.setup(1.0)
pop = sim.Population(1, sim.IF_curr_exp, {}, label="pop")
pop.set(i_offset=1.0)
pop.record(["v"])

pop.set(tau_syn_E=1)
sim.run(5)
pop.set(tau_syn_E=1)
sim.run(5)
v1 = pop.spinnaker_get_data('v')

sim.reset()
pop.set(tau_syn_E=1)
sim.run(5)
pop.set(tau_syn_E=1)
sim.run(5)
v2 = pop.spinnaker_get_data('v')

sim.end()

print(v1)
print(v2)

reset() goes back to the state at the last call to set() (i.e. all the parameters AND state variables at that point).  I'm not sure this is the expected behaviour in this script... ?

**Comment by rowleya** [comment] 2019-02-26 18:23
I think we already knew that this was broken (but good to have a ticket for it).  There have been several attempts to fix it but nothing has properly addressed the issue yet...  This is linked to the fact that state variables and parameters are all tied in to a single data structure for each neuron, so treating them differently is difficult. The current execution cycle says that after a reset, load the last data specification.  Unfortunately this means that it will load the state variables too.  Another option would have been to go to the first data specification after a reset, but of course this means that set since the last run would then be broken instead!

A possible solution would be to keep track of parameters and state variables in Python, as we currently do but also keep track of the current value of the state variables at time t=0.  Note that this would need to move as the user changes the initial values, as they are allowed to do this after a reset call.  Using this, it *might* be possible to avoid a complete reload of the data and binaries; that said, we need to be careful of what happens with synaptic data if plasticity is in use.  A possible algorithm is:
1. If plasticity, stop the binaries and reload the original data spec data, and then set the state variables to t=0 and reload that data on top.  Note that parameters might have changed as well, but this should be covered by the reloading of the data.
1. If not plasticity, tell the binaries to reset the time, and set the state variables to t=0 and reload just that data.  Again the parameters might have changed but that should be covered in the reload.

I think the current reload of parameters and state variables works, though note that AD says that we shouldn't allow a setting of the state variables without a reset first (this currently works for us, so it could be a SpiNNaker "feature" but I don't mind adding an exception there...

**Comment by Christian-B** [comment] 2019-02-27 08:43
Email chain with @apdavison 
>
> Hi Andrew,
>
> Given the following toy script:
>
> sim.setup(1.0)
> pop = sim.Population(1, sim.IF_curr_exp(v=-64, tau_syn_E=1), {}, label="pop")
> pop.set(tau_syn_E=2)
> pop.initialize(v=-63)
> sim.run(100)
> pop.set(tau_syn_E=3)
> pop.initialize(v=-62)
> sim.run(100)
> # v is now 61 because of run
> pop.set(tau_syn_E=4)
> sim.run(100)
> # v is now 60 because of run
>
> sim.reset()
>
> 1. Would you expect the line
> pop.initialize(v=-62)
> to change v or not?
No. I would expect it to raise an Exception, as pop.initialize() should only be called at the start of a simulation, or after sim.reset().

The script shouldn’t even get that far, though, as “v” is not a valid parameter for IF_curr_exp.
> 2. What would you expect the value of v to be after the reset?
> -65 as that is the default
> -64 as in the constructor
> -63 as just before the first run
this one, assuming the other initialize calls are removed
> -62 as when last initialize is called 
> -61 as when last set is called
> -60 as that was the last value
>
> 3 What is now the value of  tau_syn_E?
> 5 as that is the default
> 1 as in the constructor
> 2 as just before the first run
> 4 as when last set is called

tau_syn_E = 4. reset() changes the time to zero, but doesn’t change the structure or parameters of the network.

Cheers,

Andrew

**Comment by Christian-B** [comment] 2019-02-27 08:54
I think the long term fix is to split the loading of parameters and state variables. at least logically.

On the original load (including after reset) both are passed.

On a set only the parameters a passed in again.

This way the python will always know what it needs to load/reload and so never has to read the values off the machine to do a reset.
As paramters do not change during run and state variable can not change during run and are set back to time 0 at reset.

This long term fix may have to be delayed until release 6.0.0

**Comment by rowleya** [comment] 2019-02-27 09:58
I suspect this is a good idea, but agree that it might have to wait.  My solution would work for the current code if we want to fix this before a release (but equally it might be a bit too big a change at this point).  Note that separating out things would mean that you never have to read the parameters off the machine at all, since we only do this to avoid overwriting the state variables at present.

**Comment by such-a-git** [comment] 2019-02-27 15:55
Commenting to keep track

**Comment by andrewgait** [comment] 2019-07-18 14:34
This was fixed by https://github.com/SpiNNakerManchester/sPyNNaker/pull/669, so closing.

**Closed by andrewgait** 2019-07-18 14:34 UTC
Labels: bug
